# Generated by Django 4.2.6 on 2023-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('produse', '0002_stoc_products_disponibilitate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='disponibilitate',
        ),
        migrations.AddField(
            model_name='products',
            name='stoc_disponibil',
            field=models.IntegerField(default=0),
        ),
    ]
